apiVersion: v1
kind: Service
metadata:
  name: {{ template "portalmodelo.fullname" . }}-plone
  labels:
    app: {{ template "portalmodelo.name" . }}
    chart: {{ template "portalmodelo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: "8080"
  selector:
    app: {{ template "portalmodelo.name" . }}
    release: {{ .Release.Name }}
