apiVersion: v1
kind: Service
metadata:
  name: {{ include "portalmodelo.fullname" . }}-plone
  labels:
    {{- include "portalmodelo.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: "8080"
  selector:
    {{- include "portalmodelo.ploneSelectorLabels" . | nindent 4 }}
