{{- if .Values.velero.backup.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "portalmodelo.fullname" . }}-weekdays
  namespace: {{ .Values.velero.namespace }}
spec:
  # generate a random backup time between 1 and 5 AM on weekdays
  schedule: {{ mod (randNumeric 2) 60 }} {{ mod (randNumeric 1) 6 }} * * MON,WED,FRI
  template:
    includedNamespaces:
    - {{ .Release.Namespace }}
    {{- with .Values.velero.backup.excludedResources }}
    excludedResources:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    # every weekday backup is good for the next week (7 days)
    ttl: 168h0m0s
    {{- if .Values.velero.backup.useSnapshotBackup }}
    defaultVolumesToFsBackup: false
    snapshotVolumes: true
    snapshotMoveData: {{ .Values.velero.backup.snapshotMoveData }}
    {{- else }}
    defaultVolumesToFsBackup: true
    snapshotVolumes: false
    {{- end }}
    hooks:
      resources:
      - name: repozo
        includedResources:
          - pods
        labelSelector:
          matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/name: portalmodelo
              app.kubernetes.io/component: zeoserver
        pre:
          - exec:
              command: 
                - "/bin/bash"
                - "-c"
                - "/plone/Python-2.7/bin/python /plone/instance/bin/backup" 
              timeout: 3600s
              onError: Continue
  useOwnerReferencesInBackup: false
{{- end }}