{{- if .Values.instance.zeoclient -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "portalmodelo.fullname" . }}-zeoserver
  labels:
    app: {{ template "portalmodelo.name" . }}
    chart: {{ template "portalmodelo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8100
      targetPort: 8100
      protocol: TCP
      name: "8100"
  selector:
    app: {{ template "portalmodelo.name" . }}
    release: {{ .Release.Name }}
{{- end -}}
