{{- if .Values.instance.zeoclient }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portalmodelo.fullname" . }}-zeoserver
  labels:
    {{- include "portalmodelo.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8100
      targetPort: 8100
      protocol: TCP
      name: "8100"
  selector:
    {{- include "portalmodelo.zeoserverSelectorLabels" . | nindent 4 }}
{{- end }}

