apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sapl.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sapl.name" . }}
    helm.sh/chart: {{ include "sapl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sapl.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sapl.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: {{ printf "postgresql://sapl:%s@%s:5432/sapl" .Values.sapl.adminPassword (include "postgresql.fullname" .) | quote }}
            - name: ADMIN_PASSWORD
              value: "{{ .Values.sapl.adminPassword }}"
            - name: ADMIN_EMAIL
              value: "{{ .Values.sapl.adminEmail }}"
            - name: EMAIL_SEND_USER
              value: "{{ .Values.sapl.emailSendUser }}"
            - name: DEBUG
              value: "{{ .Values.sapl.debug }}"
            - name: USE_TLS
              value: "{{ .Values.sapl.useTls }}"
            - name: EMAIL_PORT
              value: "{{ .Values.sapl.emailPort }}"
            - name: EMAIL_HOST
              value: "{{ .Values.sapl.emailHost }}"
            - name: TZ
              value: "{{ .Values.sapl.timeZone }}"
          volumeMounts:
            - mountPath: /var/interlegis/sapl/data
              name: {{ .Release.Name }}-data
            - mountPath: /var/interlegis/sapl/media
              name: {{ .Release.Name }}-media
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      volumes:
      - name: {{ .Release.Name }}-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: {{ .Release.Name }}-media
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-media
      {{- else }}
        emptyDir: {}
      {{- end }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
