# Default values for zabbix-agent.

image:
  repository: zabbix/zabbix-agent
  tag: ubuntu-4.0-latest
  pullPolicy: IfNotPresent

zabbix:
  debugLevel: 3
  enableRemoteCommands: 0
  metadataItem: system.uname
  hostnameItem: system.hostname
  refreshActiveChecks: 120
  startAgents: 10
  timeout: 30
  serverHost: localhost

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: 
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    value: "true"
  - effect: NoSchedule
    key: node-role.kubernetes.io/lb
    operator: Equal
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/lb
    operator: Equal
    value: "true"
affinity: {}
