apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "edemocracia.fullname" . }}-audiencias
spec:
  accessModes:
  - {{ .Values.audiencias.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.audiencias.persistence.size }}
{{- if .Values.audiencias.persistence.storageClass }}
{{- if (eq "-" .Values.audiencias.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.audiencias.persistence.storageClass }}"
{{- end }}
{{- end }}
