apiVersion: v1
kind: Service
metadata:
  name: {{ include "edemocracia.fullname" . }}-edemocracia
  labels:
    {{- include "edemocracia.labels" . | nindent 4 }}
    io.kompose.service: {{ include "edemocracia.fullname" . }}-edemocracia
spec:
  type: {{ .Values.edemocracia.service.type }}
  ports:
    - port: {{ .Values.edemocracia.service.port }}
      targetPort: 8000
      protocol: TCP
      name: "8000"
  selector:
    {{- include "edemocracia.selectorLabels" . | nindent 4 }}
    io.kompose.service: {{ include "edemocracia.fullname" . }}-edemocracia
