apiVersion: v1
kind: Service
metadata:
  name: {{ include "edemocracia.fullname" . }}-nginx
  labels:
    {{- include "edemocracia.labels" . | nindent 4 }}
    io.kompose.service: {{ include "edemocracia.fullname" . }}-nginx 
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "edemocracia.selectorLabels" . | nindent 4 }}
    io.kompose.service: {{ include "edemocracia.fullname" . }}-nginx
