{{- if eq .Values.wikilegis.enabled "True" }}
apiVersion: v1
kind: Service
metadata:
  name: wikilegis
  labels:
    {{- include "edemocracia.labels" . | nindent 4 }}
    io.kompose.service: {{ include "edemocracia.fullname" . }}-wikilegis
spec:
  type: {{ .Values.wikilegis.service.type }}
  ports:
    - port: {{ .Values.wikilegis.service.port }}
      targetPort: 8000
      protocol: TCP
      name: "8000"
  selector:
    {{- include "edemocracia.selectorLabels" . | nindent 4 }}
    io.kompose.service: {{ include "edemocracia.fullname" . }}-wikilegis
{{- end }}
