# Default values for zabbix-agent.

image:
  repository: zabbix/zabbix-agent
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

zabbix:
  debugLevel: 3
  enableRemoteCommands: 0
  metadataItem: system.uname
  hostnameItem: system.hostname
  refreshActiveChecks: 120
  startAgents: 10
  timeout: 30
  serverHost: localhost

podAnnotations: {}


securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: 
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 54Mi

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    value: "true"
  - effect: NoSchedule
    key: node-role.kubernetes.io/lb
    operator: Equal
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/lb
    operator: Equal
    value: "true"

affinity: {}
