apiVersion: v2
name: sapl
description: Sistema de Apoio ao Processo Legislativo (SAPL)

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 3.1.163-RC23

icon: https://git.interlegis.leg.br/SEIT/rancher-charts/raw/master/images/sapl.png

dependencies:
- name: postgresql
  version: 11.6.26
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.internal
- name: redis
  version: 20.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
