{{- if .Values.ingress.enabled -}}
{{- $fullName := include "portalmodelo.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "portalmodelo.name" . }}
    chart: {{ template "portalmodelo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: www.{{ .Values.portal.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-plone
              servicePort: 8080
{{- end }}
