apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "portalmodelo.fullname" . }}-plone
  labels:
    app: {{ template "portalmodelo.name" . }}
    chart: {{ template "portalmodelo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
  {{- if .Values.instance.zeoclient }}
    type: RollingUpdate
  {{- else }}
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "portalmodelo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "portalmodelo.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      {{- if not .Values.instance.zeoclient }}
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}-rmlock
        command:
        - "rm"
        - "-f"
        - "/data/filestorage/Data.fs.lock"
        volumeMounts:
        - mountPath: /data
          name: {{ .Release.Name }}-data
      {{- end }}
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}-initplone
        command: 
        - "mkdir"
        - "-p"
        - "/data/filestorage"
        - "/data/blobstorage"
        - "/data/instance"
        - "/data/log"
        volumeMounts:
        - mountPath: /data
          name: {{ .Release.Name }}-data
      {{- if .Values.portal.createAndUpgrade }}
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}-plonecfg
        command: [ "/configure.sh" ]
        env:
          {{- if .Values.instance.zeoclient }}
          - name: ZEO_ADDRESS
            value: {{ template "portalmodelo.fullname" . }}-zeoserver:8100
          {{- else }}
          - name: ZEO_ADDRESS
            value: ""
          {{- end }}
          - name: EMAIL
            value: {{ .Values.portal.adminEmail }}
          - name: PASSWORD
            value: {{ .Values.portal.adminPassword }}
          - name: TITLE
            value: {{ .Values.portal.title }}
          - name: DESCR
            value: {{ .Values.portal.description }}
          - name: HOSTNAME
            value: {{ .Values.portal.hostname }}
          - name: ROOTPWD
            value: {{ .Values.portal.rootPassword }}
          - name: TZ
            value: {{ .Values.portal.timeZone }}
          - name: ZODB_CACHE_SIZE
            value: {{ .Values.portal.zodbCacheSize }}
        volumeMounts:
        - mountPath: /data
          name: {{ .Release.Name }}-data
      {{- end }}
      containers:
      - env:
        {{- if .Values.instance.zeoclient }}
        - name: ZEO_ADDRESS
          value: {{ template "portalmodelo.fullname" . }}-zeoserver:8100
        - name: ZEO_SHARED_BLOB_DIR
          value: "on"
        {{- end }}
        - name: TZ
          value: {{ .Values.portal.timeZone }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}-plone
        ports:
        - containerPort: 8080
        - containerPort: 8881
        livenessProbe:
          exec:
            command:
            - /plone/instance/bin/instance
            - monitor
            - health_ok
          initialDelaySeconds: 180
          failureThreshold: 2
          periodSeconds: 400
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
{{ toYaml .Values.resources.plone | indent 10 }}
        volumeMounts:
        - mountPath: /data
          name: {{ .Release.Name }}-data
      restartPolicy: Always
      volumes:
      - name: {{ .Release.Name }}-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
