apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.volume.storageClass }}
  name: {{ .Release.Name }}-data 
spec:
  accessModes:
  - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
