{{- if .Values.velero.backup.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "osticket.fullname" . }}-weekdays
  namespace: {{ .Values.velero.namespace }}
spec:
  # generate a random backup time between 1 and 5 AM on weekdays
  schedule: {{ mod (randNumeric 2) 60 }} {{ mod (randNumeric 1) 6 }} * * 1-5
  template:
    includedNamespaces:
    - {{ .Release.Namespace }}
    {{- with .Values.velero.backup.excludedResources }}
    excludedResources:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    snapshotVolumes: {{ .Values.velero.backup.snapshotVolumes }}
    # every weekday backup is good for the next week (7 days)
    ttl: 168h0m0s
    defaultVolumesToRestic: {{ .Values.velero.backup.defaultVolumesToRestic }}
    hooks:
      resources:
      - name: mysqldump
        includedResources:
          - pods
        labelSelector:
          matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/name: mariadb
        pre:
          - exec:
              command: 
                - "/bin/bash"
                - "-c"
                - "/opt/bitnami/mariadb/bin/mysqldump osticket -u osticket -p$MARIADB_PASSWORD > /bitnami/mariadb/osticket.dump"
              timeout: 360s
              onError: Continue
  useOwnerReferencesInBackup: false
{{- end }}