# Default values for oscm.
replicaCount: 1

image:
  repository: servicecatalog/oscm-core
  tag: latest
  pullPolicy: IfNotPresent

initdb:
  repository: servicecatalog/oscm-initdb
  tag: latest
  pullPolicy: IfNotPresent

kafka:
  repository: servicecatalog/kafka
  tag: latest
  pullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    enabled: true
    size: 10Gi
    acccessMode: ReadWriteOnce
    #storageClass:

zookeeper:
  repository: zookeeper
  tag: 3.4.10
  pullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    enabled: true
    size: 10Gi
    acccessMode: ReadWriteOnce
    #storageClass:

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hostname: localhost
  tls: false

smtp:
  host: localhost
  port: 25
  from: oscm@localhost
  user: ''
  password: ''
  auth: false
  tls: true

postgresql:
  image:
    tag: 9.6.11-r7
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 10Gi
  postgresqlPassword: postgres

provisioning:
  kubernetes: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
