apiVersion: v1
appVersion: "1.2.24"
description: Highly available IP addresses with VRRP
name: keepalived
icon: https://beopen.bplaced.net/wp-content/uploads/2016/11/Keepalived-logo.png
version: 0.1.1
