{{- if .Values.app.deploy -}}
  {{- if .Values.app.controller.shell.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oscm.fullname" . }}-app-scripts
spec:
  accessModes:
  - {{ .Values.app.controller.shell.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.app.controller.shell.persistence.size }}
    {{- if .Values.app.controller.shell.persistence.storageClass }}
      {{- if (eq "-" .Values.app.controller.shell.persistence.storageClass) }}
  storageClassName: ""
      {{- else }}
  storageClassName: "{{ .Values.app.controller.shell.persistence.storageClass }}"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
