{{- if .Values.app.deploy -}}
  {{- if .Values.ingress.enabled -}}
  {{- $fullName := include "oscm.fullname" . -}}
  {{- $ingressPath := .Values.app.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-app
  labels:
    app.kubernetes.io/name: {{ include "oscm.name" . }}-app
    helm.sh/chart: {{ include "oscm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- if  .Values.ingress.hostname }}
    - {{ .Values.ingress.hostname }}
    secretName: {{  .Values.ingress.tlsSecret }}
    {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-app
              servicePort: 8880
  {{- end }}
{{- end }}

