{{- if .Values.app.deploy -}}
{{- $hostname := .Values.ingress.hostname -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "oscm.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "oscm.name" . }}-app
    helm.sh/chart: {{ include "oscm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oscm.name" . }}-app
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oscm.name" . }}-app
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: "{{ .Chart.Name }}-initdb-app"
          image: "{{ .Values.initdb.repository }}:{{ .Values.initdb.tag }}"
          imagePullPolicy: {{ .Values.initdb.pullPolicy }}
          env:
          - name: TARGET
            value: "APP"
          - name: SOURCE
            value: "INIT"
          - name: AUTH_MODE
            value: "INTERNAL"
          - name: OVERWRITE
            value: "false"
          - name: DB_HOST_APP
            value: {{ template "postgresql.fullname" . }}
          - name: DB_PORT_APP
            value: {{ .Values.postgresql.service.port | quote }}
          - name: DB_PWD_APP
            value: {{ .Values.app.dbpwd | quote }}
          - name: DB_SUPERPWD
            value: {{ .Values.postgresql.postgresqlPassword | quote }}

        {{- if .Values.app.controller.shell }}
        - name: "{{ .Chart.Name }}-initdb-controller-shell"
          image: "{{ .Values.initdb.repository }}:{{ .Values.initdb.tag }}"
          imagePullPolicy: {{ .Values.initdb.pullPolicy }}
          env:
          - name: TARGET
            value: "CONTROLLER"
          - name: SOURCE
            value: "NONE"
          - name: AUTH_MODE
            value: "INTERNAL"
          - name: OVERWRITE
            value: "true"
          - name: CONTROLLER_ID
            value: "ess.shell"
          - name: CONTROLLER_ORG_ID
            value: {{ .Values.app.controller.orgId | quote }}
          - name: CONTROLLER_USER_KEY
            value: {{ .Values.app.controller.userKey | quote }}
          - name: CONTROLLER_USER_NAME
            value: {{ .Values.app.controller.userName | quote }} 
          - name: CONTROLLER_USER_PASS
            value: {{ .Values.app.controller.userPass | quote }}
          - name: DB_HOST_APP
            value: {{ template "postgresql.fullname" . }}
          - name: DB_PORT_APP
            value: {{ .Values.postgresql.service.port | quote }}
          - name: DB_PWD_APP
            value: {{ .Values.app.dbpwd | quote }}
          - name: DB_SUPERPWD
            value: {{ .Values.postgresql.postgresqlPassword | quote }}
        {{- end }} 

      containers:
        - name: {{ include "oscm.name" . }}-app
          image: "{{ .Values.app.repository }}:{{ .Values.app.tag }}"
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          env:
          - name: DB_HOST_APP
            value: {{ template "postgresql.fullname" . }}
          - name: DB_PORT_APP
            value: {{ .Values.postgresql.service.port | quote }}
          - name: DB_PWD_APP
            value: {{ .Values.app.dbpwd | quote }}
          - name: DB_SUPERPWD
            value: {{ .Values.postgresql.postgresqlPassword | quote }}
          - name: APP_ADMIN_MAIL_ADDRESS
            value: {{ .Values.smtp.from | quote }}
          - name: SMTP_HOST
            value: "{{ .Values.smtp.host }}"
          - name: SMTP_PORT
            value: "{{ .Values.smtp.port }}"
          - name: SMTP_FROM
            value: "{{ .Values.smtp.from }}"
          - name: SMTP_USER
            value: "{{ .Values.smtp.user }}"
          - name: SMTP_PWD
            value: "{{ .Values.smtp.password }}"
          - name: SMTP_AUTH
            value: "{{ .Values.smtp.auth }}"
          - name: SMTP_TLS_ENABLE
            value: "{{ .Values.smtp.tls }}"
          {{- if .Values.debug }}
          - name: TOMEE_DEBUG
            value: "true"
          - name: LOG_LEVEL
            value: "DEBUG"
          {{- end }}
          ports:
          - name: http-port
            containerPort: 8080
          - name: https-port
            containerPort: 8081
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

{{- end }}
