{{- $hostname := .Values.ingress.hostname -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "oscm.fullname" . }}-core
  labels:
    app.kubernetes.io/name: {{ include "oscm.name" . }}-core
    helm.sh/chart: {{ include "oscm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oscm.name" . }}-core
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oscm.name" . }}-core
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: "{{ .Chart.Name }}-initdb-core"
          image: "{{ .Values.initdb.repository }}:{{ .Values.initdb.tag }}"
          imagePullPolicy: {{ .Values.initdb.pullPolicy }}
          env:
          - name: TARGET
            value: "CORE"
          - name: SOURCE
            value: "INIT"
          - name: AUTH_MODE
            value: "INTERNAL"
          - name: DB_HOST_CORE
            value: {{ template "postgresql.fullname" . }}
          - name: DB_PORT_CORE
            value: {{ .Values.postgresql.service.port | quote }}
          - name: DB_SUPERPWD
            value: {{ .Values.postgresql.postgresqlPassword | quote }}
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: {{ include "oscm.name" . }}-kafka:9092
          - name: BASE_URL
            value: "http://{{ $hostname }}:8080/oscm-portal"
          - name: BASE_URL_HTTPS
            value: "https://{{ $hostname }}:8081/oscm-portal"
        - name: "{{ .Chart.Name }}-initdb-jms"
          image: "{{ .Values.initdb.repository }}:{{ .Values.initdb.tag }}"
          imagePullPolicy: {{ .Values.initdb.pullPolicy }}
          env:
          - name: TARGET
            value: "JMS"
          - name: SOURCE
            value: "INIT"
          - name: DB_HOST_JMS
            value: {{ template "postgresql.fullname" . }}
          - name: DB_PORT_JMS
            value: {{ .Values.postgresql.service.port | quote }}
          - name: DB_SUPERPWD
            value: {{ .Values.postgresql.postgresqlPassword | quote }}
          - name: OVERWRITE
            value: "true"

      containers:
        - name: {{ include "oscm.name" . }}-core
          hostname: oscm-core
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB_HOST_CORE
            value: {{ template "postgresql.fullname" . }}
          - name: DB_HOST_JMS
            value: {{ template "postgresql.fullname" . }}
          - name: DB_TIMEOUT_CORE
            value: "5"
          - name: DB_WAIT_CORE
            value: "5000"
          - name: DB_RETRY_INTERVAL_CORE
            value: "3"
          - name: DB_TIMEOUT_MI
            value: "5"
          - name: DB_WAIT_MI
            value: "5000"
          - name: DB_RETRY_INTERVAL_MI
            value: "3"
          - name: SMTP_HOST
            value: "{{ .Values.smtp.host }}"
          - name: SMTP_PORT
            value: "{{ .Values.smtp.port }}"
          - name: SMTP_FROM
            value: "{{ .Values.smtp.from }}"
          - name: SMTP_USER
            value: "{{ .Values.smtp.user }}"
          - name: SMTP_PWD
            value: "{{ .Values.smtp.password }}"
          - name: SMTP_AUTH
            value: "{{ .Values.smtp.auth }}"
          - name: SMTP_TLS_ENABLE
            value: "{{ .Values.smtp.tls }}"
          {{- if .Values.debug }}
          - name: TOMEE_DEBUG
            value: "true"
          - name: LOG_LEVEL
            value: "DEBUG"
          {{- end }}
          ports:
          - name: http-port
            containerPort: 8080
          - name: https-port
            containerPort: 8081
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
