{{- $hostname := .Values.ingress.hostName -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "oscm.fullname" . }}-initdb
  labels:
    app.kubernetes.io/name: {{ include "oscm.name" . }}
    helm.sh/chart: {{ include "oscm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oscm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      name: {{ include "oscm.fullname" . }}-initdb
    spec:
      containers:
        - name: "{{ .Chart.Name }}-initdb"
          image: "{{ .Values.initdb.repository }}:{{ .Values.initdb.tag }}"
          imagePullPolicy: {{ .Values.initdb.pullPolicy }}
          env:
          - name: TARGET
            value: "CORE"
          - name: SOURCE
            value: "INIT"
          - name: AUTH_MODE
            value: "INTERNAL"
          - name: DB_HOST_BES
            value: {{ template "postgresql.fullname" . }}
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka:9092"
          - name: BASE_URL
            value: "http://{{ $hostname }}:8080/oscm-portal"
          - name: BASE_URL_HTTPS
            value: "https://{{ $hostname }}:8081/oscm-portal"
          - name: REPORT_ENGINEURL
            value: "https://{{ $hostname }}/birt/frameset?__report=${reportname}.rptdesign&SessionId=${sessionid}&__locale=${locale}&WSDLURL=${wsdlurl}&SOAPEndPoint=${soapendpoint}&wsname=ReportSecure&wsport=ReportSecurePort"
          - name: REPORT_WSDLURL
            value: "https://{{ $hostname }}/ReportSecure/ReportingServiceSecureBean?wsdl"
          - name: REPORT_SOAP_ENDPOINT
            value: "https://{{ $hostname }}/ReportSecure/ReportingServiceSecureBean"
          - name: SSO_STS_URL
            value: "https://{{ $hostname }}/adfs/services/trust/13/usernamemixed"
          - name: SSO_STS_METADATA_URL
            value: "https://{{ $hostname }}/adfs/services/trust/mex"
          - name: SSO_DEFAULT_TENANT_ID
            value: "oscmaas1"
          - name: SSO_IDP_SAML_ASSERTION_ISSUER_ID
            value: "http://{{ $hostname }}/adfs/services/trust"
          - name: SSO_LOGOUT_URL
            value: "https://{{ $hostname }}/adfs/ls/"

      nodeSelector:
    {{- with .Values.nodeSelector }}
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
