apiVersion: v2
name: portalmodelo
description: Portal Modelo para Casas Legislativas
type: application
version: 0.5.0
appVersion: 3.0-21
icon: https://git.interlegis.leg.br/SEIT/rancher-charts/raw/5a821368fe0244ae9017878dd2aae3173328816c/images/portalmodelo.png
